# Generated by Django 5.0.1 on 2024-03-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='professionalExperience',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='professional_experience',
            new_name='designation',
        ),
    ]
