# Generated by Django 5.0.1 on 2024-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_professionalexperience_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teachers/images/'),
        ),
    ]
