# Generated by Django 5.0.1 on 2024-03-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoClass', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='DemoClass',
        ),
    ]
